# OpsDeck shell integration for zsh
ZDOTDIR="$__opsdeck_user_zdotdir"
[[ "$ZDOTDIR" == "$HOME" ]] && unset ZDOTDIR
[[ -f "${ZDOTDIR:-$HOME}/.zshrc" ]] && source "${ZDOTDIR:-$HOME}/.zshrc"

if [[ -z "$__OPSDECK_SI" ]]; then
  __OPSDECK_SI=1
  autoload -Uz add-zsh-hook
  __opsdeck_precmd() {
    local ec=$?
    print -n "\e]133;D;${ec}\a\e]133;A\a\e]7;file://${HOST}${PWD}\a"
  }
  __opsdeck_preexec() {
    print -n "\e]133;E;$(print -rn -- "$1" | base64 -w0)\a\e]133;C\a"
  }
  add-zsh-hook precmd __opsdeck_precmd
  add-zsh-hook preexec __opsdeck_preexec
  PS1="${PS1}%{"$'\e]133;B\a'"%}"
fi
